// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHaWQRYdcgVRED6cufwfO9N971MHdCGSE',
    appId: '1:1095357279136:web:c03dd92f18aa58b965d2c5',
    messagingSenderId: '1095357279136',
    projectId: 'ayaresapa',
    authDomain: 'ayaresapa.firebaseapp.com',
    storageBucket: 'ayaresapa.appspot.com',
    measurementId: 'G-S1N4SNHVCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtk9uujsnDOXdkiOtv1N3PkWb__ab-Ihk',
    appId: '1:1095357279136:android:a24d3ab9ee9cd7d565d2c5',
    messagingSenderId: '1095357279136',
    projectId: 'ayaresapa',
    storageBucket: 'ayaresapa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtWJiwgv0KEjf_YtMzGGm-h5IEkR0IrYQ',
    appId: '1:1095357279136:ios:0f66461f89f6785565d2c5',
    messagingSenderId: '1095357279136',
    projectId: 'ayaresapa',
    storageBucket: 'ayaresapa.appspot.com',
    androidClientId: '1095357279136-a631f690vfhbu2a1goue3vb50r77vv4o.apps.googleusercontent.com',
    iosClientId: '1095357279136-g02rovjqmco6fb0dtultrot3ff0bg61e.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtWJiwgv0KEjf_YtMzGGm-h5IEkR0IrYQ',
    appId: '1:1095357279136:ios:0f66461f89f6785565d2c5',
    messagingSenderId: '1095357279136',
    projectId: 'ayaresapa',
    storageBucket: 'ayaresapa.appspot.com',
    androidClientId: '1095357279136-a631f690vfhbu2a1goue3vb50r77vv4o.apps.googleusercontent.com',
    iosClientId: '1095357279136-g02rovjqmco6fb0dtultrot3ff0bg61e.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctor',
  );
}
